### ISSUE TITLE
Add Readme file to your folder

### ISSUE THREAD

**Issue by oladhari** [yuya417/Myportfolio_2#4]
please add a readme file to your project with details of :

- [x] used technologies
- [x] purpose of the project
- [ ] link to the hosted web page of this folder

[here](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2) a template of Readme file

**Comment by yuya417** [comment]
@oladhari 
Thank you!

**Comment by oladhari** [comment]
you can close the issue when you finish the related PR
why did you close the issue?

**Comment by yuya417** [comment]
関連するPRとはなんですか？

**Comment by oladhari** [comment]
you should create new PR to add or update the README file
create a branch and update the readme file, then push and accept the PR in your Github folder
